const config = {};

config.IS_TESTNET = process.env.IS_TESTNET === 'TRUE';

config.FIRESTORE_USER_ROOT = process.env.FIRESTORE_USER_ROOT;
config.FIRESTORE_WALLET_USER_ROOT = process.env.FIRESTORE_WALLET_USER_ROOT;

config.LIKE_CO_CLIENT_ID = process.env.LIKE_CO_CLIENT_ID;
config.LIKE_CO_CLIENT_SECRET = process.env.LIKE_CO_CLIENT_SECRET;

config.COOKIE_SECRET = process.env.COOKIE_SECRET;

config.CRISP_USER_HASH_SECRET = process.env.CRISP_USER_HASH_SECRET;
config.CRISP_PLUGIN_IDENTIFIER = process.env.CRISP_PLUGIN_IDENTIFIER;
config.CRISP_PLUGIN_KEY = process.env.CRISP_PLUGIN_KEY;
config.CRISP_WEBSITE_ID = process.env.CRISP_WEBSITE_ID;

config.LIKECOIN_CHAIN_API = process.env.LIKECOIN_CHAIN_API;
config.LIKECOIN_API_BASE = process.env.LIKECOIN_API_BASE;
config.EXTERNAL_URL = process.env.EXTERNAL_URL;

config.GET_WALLET_API_SECRET = process.env.GET_WALLET_API_SECRET;

config.LIKECOIN_NFT_API_WALLET = process.env.LIKECOIN_NFT_API_WALLET;

config.AIRTABLE_API_SECRET = process.env.AIRTABLE_API_SECRET;
config.AIRTABLE_CMS_BASE_ID = process.env.AIRTABLE_CMS_BASE_ID;
config.AIRTABLE_CMS_PRODUCTS_TABLE_ID =
  process.env.AIRTABLE_CMS_PRODUCTS_TABLE_ID;
config.AIRTABLE_CMS_PRODUCTS_CHAIN_TYPE =
  process.env.AIRTABLE_CMS_PRODUCTS_CHAIN_TYPE;
config.AIRTABLE_CMS_TAGS_TABLE_ID = process.env.AIRTABLE_CMS_TAGS_TABLE_ID;

config.AUTHCORE_PUBLIC_KEY = process.env.AUTHCORE_PUBLIC_KEY;

module.exports = config;
