export const READER_ADD_USER = 'READER_ADD_USER';
export const READER_SET_USER_LIST = 'READER_SET_USER_LIST';
export const READER_REMOVE_USER = 'READER_REMOVE_USER';
export const READER_ADD_UNSUB_USER = 'READER_ADD_UNSUB_USER';
export const READER_SET_UNSUB_USER_LIST = 'READER_SET_UNSUB_USER_LIST';
export const READER_REMOVE_USER_UNSUB_USER = 'READER_REMOVE_USER_UNSUB_USER';
export const READER_UPDATE_USER_URL = 'READER_UPDATE_USER_URL';
export const READER_REMOVE_USER_URL = 'READER_REMOVE_USER_URL';

export const UI_TOGGLE_SLIDING_MENU = 'UI_TOGGLE_SLIDING_MENU';

export const USER_SET_USER_INFO = 'USER_SET_USER_INFO';
export const USER_UPDATE_USER_INFO = 'USER_UPDATE_USER_INFO';
