export const READER_ADD_FOLLOW_USER = 'READER_ADD_FOLLOW_USER';
export const READER_SET_FOLLOW_USER_LIST = 'READER_SET_FOLLOW_USER_LIST';
export const READER_REMOVE_FOLLOW_USER = 'READER_REMOVE_FOLLOW_USER';
export const READER_ADD_UNFOLLOW_USER = 'READER_ADD_UNFOLLOW_USER';
export const READER_SET_UNFOLLOW_USER_LIST = 'READER_SET_UNFOLLOW_USER_LIST';
export const READER_REMOVE_UNFOLLOW_USER = 'READER_REMOVE_UNFOLLOW_USER';
export const READER_UPDATE_USER_ARTICLES = 'READER_UPDATE_USER_ARTICLES';
export const READER_REMOVE_USER_ARTICLES = 'READER_REMOVE_USER_ARTICLES';
export const READER_SET_FOLLOWED_ARTICLES = 'READER_SET_FOLLOWED_ARTICLES';
export const READER_APPEND_FOLLOWED_ARTICLES =
  'READER_APPEND_FOLLOWED_ARTICLES';
export const READER_SET_SUGGEST_ARTICLES = 'READER_SET_SUGGEST_ARTICLES';
export const READER_SET_BOOKMARK = 'READER_SET_BOOKMARK';
export const READER_ADD_BOOKMARK = 'READER_ADD_BOOKMARK';
export const READER_REMOVE_BOOKMARK = 'READER_REMOVE_BOOKMARK';
export const READER_CLEAR_FOR_LOGOUT = 'READER_CLEAR_FOR_LOGOUT';

export const SUPPORT_SET_SUPPORTING_USERS = 'SUPPORT_SET_SUPPORTING_USERS';
export const SUPPORT_SET_SUPPORTING_USER_INFO =
  'SUPPORT_SET_SUPPORTING_USER_INFO';
export const SUPPORT_REMOVE_SUPPORTING_USER = 'SUPPORT_REMOVE_SUPPORTING_USER';
export const SUPPORT_SET_SUPPORTERS = 'SUPPORT_SET_SUPPORTERS';

export const STATIC_SET_USER_INFO = 'STATIC_SET_USER_INFO';
export const STATIC_SET_ARTICLE_INFO = 'STATIC_SET_ARTICLE_INFO';
export const STATIC_SET_USER_FETCHING = 'STATIC_SET_USER_FETCHING';
export const STATIC_SET_NFT_CLASS_PURCHASE_INFO =
  'STATIC_SET_NFT_CLASS_PURCHASE_INFO';
export const STATIC_SET_NFT_CLASS_METADATA = 'STATIC_SET_NFT_CLASS_METADATA';
export const STATIC_SET_NFT_CLASS_OWNER_INFO =
  'STATIC_SET_NFT_CLASS_OWNER_INFO';

export const UI_SET_LOCALE = 'UI_SET_LOCALE';
export const UI_TOGGLE_SLIDING_MENU = 'UI_TOGGLE_SLIDING_MENU';
export const UI_SET_IS_HK = 'UI_SET_IS_HK';
export const UI_TOGGLE_SNACKBAR = 'UI_TOGGLE_SNACKBAR';
export const UI_SET_ALERT_TYPE = 'UI_SET_ALERT_TYPE';
export const UI_SET_ALERT_MESSAGE = 'UI_SET_ALERT_MESSAGE';
export const UI_TOGGLE_COLLECT_MODAL = 'UI_TOGGLE_COLLECT_MODAL';
export const UI_SET_COLLECT_OWNED_COUNT = 'UI_SET_COLLECT_OWNED_COUNT';
export const UI_SET_TX_STATUS = 'UI_SET_TX_STATUS';
export const UI_SET_TX_ERROR_MESSAGE = 'UI_SET_TX_ERROR_MESSAGE';

export const USER_SET_USER_INFO = 'USER_SET_USER_INFO';
export const USER_UPDATE_USER_INFO = 'USER_UPDATE_USER_INFO';
export const USER_SET_SUBSCRIPTION_INFO = 'USER_SET_SUBSCRIPTION_INFO';

export const WALLET_SET_ADDRESS = 'WALLET_SET_ADDRESS';
export const WALLET_SET_SIGNER = 'WALLET_SET_SIGNER';
export const WALLET_SET_METHOD = 'WALLET_SET_METHOD';
export const WALLET_SET_CONNECTOR = 'WALLET_SET_CONNECTOR';
export const WALLET_SET_LIKERINFO = 'WALLET_SET_LIKERINFO';
