export const READER_UPDATE_USER_LIST = 'READER_UPDATE_USER_LIST';
export const READER_UPDATE_USER_URL = 'READER_UPDATE_USER_URL';
export const USER_SET_USER_INFO = 'USER_SET_USER_INFO';
export const USER_SET_ACCESS_TOKEN = 'USER_SET_ACCESS_TOKEN';
